### ISSUE TITLE
Text styling support is missing

### ISSUE THREAD

**Issue by gevorgyanvahagn** [sergpetrov/fastlane-plugin-telegram#12]
It would be great to have an option to pass **parse_mode** to the call, so the users will have more control over the styling. As an option default style can be **markdown**

**Comment by gevorgyanvahagn** [comment]
Oh, I see it's already implemented, I'll try to figure out why it's not working for me

**Comment by Alex-Alex77** [comment]
@gevorgyanvahagn Markdown is not working for me. Did you solve it?

**Comment by gevorgyanvahagn** [comment]
> @gevorgyanvahagn Markdown is not working for me. Did you solve it?

Hey Alex, honestly I don't remember, will check on the evening and will comment here
