### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by NikKovIos** [sergpetrov/fastlane-plugin-telegram#2]
Hello there, two questions:
Does it work?
How to configure it?

**Comment by sergpetrov** [comment]
@NikKovIos Hi. Yes.
You can add into your Fastfile something like that
telegram(
        token: "yourToken",
        chat_id: "yourTelegramChatId",
        text: "message"
  )

**Comment by NikKovIos** [comment]
Could you please clear how to get this parameters? Not for me but for other, who gonna search it? 
And where can i find plugin parameters list?

**Comment by sergstav** [comment]
@NikKovIos step by step:
1. For obtain token, you should go to the Telegram, then search for BotFather, click start, then choose Create new bot, follow necessary steps, and you will see token for you bot.
2. For obtain chat id, go to the Telegram, search for @get_id_bot, and click start, wait few seconds, and you will see chatId. 
Use this token & chatId for sending messages from fastlane to telegram, checked it successfully.

**Comment by anhtuank7c** [comment]
@sergstav Seem **get_id_bot** stop working

![image](https://user-images.githubusercontent.com/3163410/86068113-b0163300-baa0-11ea-9eff-b582589fb86e.png)
