### ISSUE TITLE
Is it possible to provide proxy settings when executing this action?

### ISSUE THREAD

**Issue by zigdanis** [sergpetrov/fastlane-plugin-telegram#3]
Telegram is blocked in Russia so we need to use proxy or VPN in order to access it.
It would be great to have built-in proxy setting for this plugin, so all the other actions requests in fastlane could be accessed directly.
I've tried to use .pac file in MacOS Network Settings in order to bypass with proxy only "telegram.org" urls, but it appear that underlying ruby network requests ignores that.
I don't know ruby, but if you're not intend to do it - than maybe I would try to make a PR for this 😃

**Comment by sergpetrov** [comment]
Hi!. 
Yes, make PR please!

**Comment by zigdanis** [comment]
@sergpetrov I've managed to create PR for this issue #4 
Please, take a look.
