### ISSUE TITLE
Proxy doesn't work

### ISSUE THREAD

**Issue by NEXTKING** [sergpetrov/fastlane-plugin-telegram#5]
Hello, this one is nice but when I try to add proxy I get this:

**Could not find option 'proxy' in the list of available options: token, chat_id, text**

I'm using v. 0.1.2, the latest for now I guess

**Comment by aleksandrshoshiashvili** [comment]
@sergpetrov same problem

**Comment by sergpetrov** [comment]
Hi guys, make pull request with fix if you are available please.
Thanks!

**Comment by aleksandrshoshiashvili** [comment]
Awesome, thank you @sergpetrov ! 🎉
